/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: hashup (https://sketchfab.com/hashup)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hashupcartdridge-gold-6c8fa82a761a4392a10b87257d797683
title: HashUpCartdridge_Gold
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
    const group = useRef()
    const mesh = useRef()
    const { nodes, materials } = useGLTF('/assets/models/scene/scene.gltf')

    useEffect(() => {
        mesh.current.geometry.center()
    }, [])

    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={.15}>
                    <mesh
                        geometry={nodes.NESCartridge_low_NESCartridge_0.geometry}
                        material={materials.NESCartridge}
                        rotation={[Math.PI / 6, -Math.PI / 6, 0]}
                        ref={mesh}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/assets/models/scene/scene.gltf')
