/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/assets/models/suzanne/suzanne.gltf')
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh geometry={nodes.Suzanne.geometry} material={nodes.Suzanne.material} position={[0, 0.19, -0.04]} />
        </group>
    )
}

useGLTF.preload('/assets/models/suzanne/suzanne.gltf')
